### ISSUE TITLE
DLT & the Law: current challenges, legislators trends and future opportunities 

### ISSUE THREAD

**Issue by GibSensE** [wslyvh/dutchblockchainweek#10]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: DLT & the Law: current challenges, legislators trends and future opportunities 

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: DLT & the Law: current challenges, legislators trends and future opportunities 

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: DLT & the Law: current challenges, legislators trends and future opportunities 

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    We need new laws they say, but do we really need them to keep moving? From the GDPR apparent clash with blockchain’s immutability, to the question of ownership of a self-sovereign ledgers, to the question of enforceability of smart contracts, do we really need the legislators’ intervention or can we actually work around existing laws in order to keep building disruptive technologies? With a positive mindset aiming at finding solutions to foster tech innovation for the benefit of society, Alessandro Mazzi will guide you through some of the legal challenges blockchain is currently facing, and what he believes are the most interesting opportunities the law could offer to blockchain entrepreneurs in the future.
  

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2019-06-03
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate:

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '14:45'
# Time when the event ends. Can be left empty.
endTime: '15:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: 

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price:

# The name of the venue where the event will be held. Can be left empty.
venue: VU Amsterdam, HG-08A20

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: De Boelelaan 1105, 1081 HV Amsterdam

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - panel
# - workshop
# Use _only_ one, and don't capitalize.
category: event

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    # Required.
    name: Alessandro Mazzi

    # Can be left empty.
    title: Legal Advisor | RegTech | Blockchain & DLT Consultant

    # Can be left empty.
    company: AM Legal

    # The full URL, including http(s)://. Can be left empty.
    companyURL: https://www.alessandromazzilegal.com/

    # Just the twitter handle, without Twitter's URL, nor the '@' symbol.
    # Can be left empty.
    twitter: 

    # The full URL, including http(s)://. Can be left empty.
    website: 

    # The bio is a single line.
    # Linebreaks are ignored, but they _must_ start with two spaces.
    bio: Alessandro Mazzi is a creative legal expert with a professional passion for freedom projects, disruptive technologies, future-proof businesses and, regulatory challenges. He established AM Legal in 2015, with the aim to serve, from a very early age, game-changing projects with solution-driven legal advice. AM Legal practice focuses on Commercial Contracting, IP strategy, Blockchain projects, RegTech, Alternative Dispute Resolution, Commercial Mediation, Partnership Agreements, EU Privacy Compliance. Aside from his day-to-day practice, He is interested in ocean conservation, climate change litigation and green tech. 

  -
    name: Alessandro Mazzi
    title: Legal Advisor
    company: AM Legal
    companyURL: https://www.alessandromazzilegal.com/
    bio: Alessandro Mazzi is a creative legal expert with a professional passion for freedom projects, disruptive technologies, future-proof businesses and, regulatory challenges. He established AM Legal in 2015, with the aim to serve, from a very early age, game-changing projects with solution-driven legal advice. AM Legal practice focuses on Commercial Contracting, IP strategy, Blockchain projects, RegTech, Alternative Dispute Resolution, Commercial Mediation, Partnership Agreements, EU Privacy Compliance. Aside from his day-to-day practice, He is interested in ocean conservation, climate change litigation and green tech. 
  
 

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by wslyvh** [comment]
Added.

https://www.dutchblockchainweek.com/events/law/
