### ISSUE TITLE
Meet the builders: VMC + COSMOS + MOBOTIQ

### ISSUE THREAD

**Issue by jochemverheul** [wslyvh/dutchblockchainweek#13]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

May 21, 2019 
Are you ready for a technical deepdive? Together with the Dutch Blockchain Week, we are organising a Meetup for people who are interested in building blockchain applications. We will share our experiences in the challenges we faced getting our implementations live and explain how to actually get applications live. Everybody is welcome. Recruiting and sales is not allowed. After the Meetup we will drink a few beers together.

Arrival: 16.00
Start of the programme: 16:30
End: 18:30

Max Mijnheer / VMC
Max is Lead Architect at VMC. Max has been involved with VMC from the very beginning. Max will explain in depth how VMC developed the first operational implementation in public transport. Although we used many open source components, the VMC stack is developed more or less from scratch. To get this technology in the hands of actual people required lots of work and innovations. Max will share his learnings, best practises and the stories behind this implementation.

Billy Rennekamp / Cosmos
Billy Rennekamp is an artist and developer. He works on a variety of projects including Cosmos and Tendermint. In this workshop, Billy will explain how to create a functional nameservice application. In the process, you will learn the basic concepts of Cosmos and structures of the SDK.

Thomas Cocirta
Thomas is an engineer and inventor. He is the intellect behind the autonomous robotaxi company Mobotiq. With Mobotiq, Thomas has produced self driving vehicles of which many parts can be produced via 3D printers. Thomas will share his vision on how 3D printing, robots and blockchain are together changing the world of (mass)production forever.

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Sample Template

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: This is a talk about blockchain. This field is indexed by search
  engines and used to show a description on /events.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Sample Template

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    Short synopsis of the event goes here. This is the first paragraph.
  -
    Dolor officiis aliquam eligendi adipisci debitis. Accusamus quis ratione
      perferendis esse nam. Vero itaque quidem molestias id quo? Deleniti ipsum
      nobis magni illum quos architecto omnis Modi reprehenderit inventore!
  -
    This is the third paragraph. Add more as needed...

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-09-05
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2018-09-05

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '20:00'
# Time when the event ends. Can be left empty.
endTime: '22:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://eventbrite.com/my-event

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 5

# The name of the venue where the event will be held. Can be left empty.
venue: FULL NODE

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: Skalitzer Strasse 85-86, 10997 Berlin, Germany

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - panel
# - workshop
# Use _only_ one, and don't capitalize.
category: event

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    # Required.
    name: Carlos E. Salazar

    # Can be left empty.
    title: Lead Front-end Developer

    # Can be left empty.
    company: Least Authority

    # The full URL, including http(s)://. Can be left empty.
    companyURL: https://leastauthority.com

    # Just the twitter handle, without Twitter's URL, nor the '@' symbol.
    # Can be left empty.
    twitter: cesalazar

    # The full URL, including http(s)://. Can be left empty.
    website: https://cesalazar.com

    # The bio is a single line.
    # Linebreaks are ignored, but they _must_ start with two spaces.
    bio: Here goes Carlos' description. Amet corporis laudantium obcaecati
      perferendis reiciendis rem perferendis. Magni qui reiciendis explicabo.
  -
    name: Vitalik Buterin
    title: Co-founder
    company: Ethereum
    companyURL: https://ethereum.org/
    twitter: VitalikButerin
    website: https://vitalik.ca
    bio: Vitalik Buterin is a Russian-Canadian programmer and writer primarily
      known as a co-founder of Ethereum and as a co-founder of Bitcoin Magazine.
  -
    name: Kathleen Breitman
    title: CEO
    company: Tezos
    companyURL: https://tezos.com/
    twitter: breitwoman
    website: http://kathleenbreitman.com
    bio: Co-founder at Tezos, a fresh implementation of a blockchain which can
      amend its protocol.

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by wslyvh** [comment]
Hi Jochem, do you have more info or a link to the original event? 
I don't think 21st of May, is correct? All other values are still filled with the sample data..

**Comment by jochemverheul** [comment]
Hi Wesley,

Here you go; https://vmc.ai/news-meet-the-builders-vmc-cosmos-mobotiq/

Best,

**Comment by wslyvh** [comment]
Thanks. Added!
https://www.dutchblockchainweek.com/events/vmc/

**Comment by jochemverheul** [comment]
Thanks!
