### ISSUE TITLE
The WorkFork Online Hackathon

### ISSUE THREAD

**Issue by alc-nmff** [wslyvh/dutchblockchainweek#14]
title: The WorkFork Online Hackathon

description: Showcase your skills in this online Hackathon organised by WorkFork in collaboration with Research Institute, Ergo Platform, Pisa Research and others.

name: The WorkFork Online Hackathon

synopsis:
  -
    Showcase your skills in this online Hackathon organised by WorkFork in collaboration with Research Institute, Ergo Platform, Pisa Research and others.
-
Prizes include: total prize pool is over EUR 5000
-
Participants will be notified of the results of the hackathon by 20:00 UTC+2 on 2019-06-17
Please note, participants can only compete as individuals. 
-
If you are looking for a new challenge or change of pace career-wise, please be sure to check out the vacancies available on the WorkFork platform. 

date: 2019-06-06
endDate: 2019-06-14

time: '12:00'

endTime: '20:00'

tickets: https://workfork.io/hackathon_dutchblockchainweek

price: 0

venue: Online

address: 

category: hackathon

speakers:

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by wslyvh** [comment]
Added.

https://www.dutchblockchainweek.com/events/workfork/
