### ISSUE TITLE
Hybrix Get-Together

### ISSUE THREAD

**Issue by Dotrego** [wslyvh/dutchblockchainweek#16]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---

title: Hybrix - Blockchain get-together

description: Join the hybrix monthly get-together if you are interested in blockchain technology and coding, want to talk about it, share your experiences, pains or want to learn more.

name: Hybrix Get-Together

synopsis: Join the hybrix monthly get-together if you are interested in blockchain technology and coding, want to talk about it, share your experiences, pains or want to learn more.
  -
    This edition is hosted in cooperation with Blockchain Netherlands for the Dutch Blockchain Week.
For more information visit https://www.dutchblockchainweek.com
  -
    Join the hybrix monthly get-together if you are interested in blockchain technology and coding, want to talk about it, share your experiences, pains or want to learn more. Come for a drink and a chat at the Lisk Center Utrecht!
  -
    After the meet, we welcome guests to join the Utrecht Crypto Café community for a panel discussion on the societal impact of decentralization at restaurant Puschkin, 20.00.
For more information visit https://www.facebook.com/CryptoCafe24/

endDate: 2019-06-06

time: '17:00'
endTime: '19:00'

tickets: https://www.meetup.com/LiskCenterUtrecht/events/261671551/

price: 0

venue: Lisk Center Utrecht

address: Jaarbeursplein 6, 3521 AL Utrecht

category: event

speakers:
  -
    name: Joachim de Koning
    title: Founder
    company: hybrix
    companyURL: https://hybrix.io
    twitter:
    website: https://www.linkedin.com/in/joachim-de-koning-a5874b25/
    bio: Founder of hybrix, the open source blockchain agnostic development platform.
  -
    name: Robert de Groot
    title: Co-Founder
    company: hybrix
    companyURL: https://hybrix.io
    twitter: RobDotrego
    website: https://www.linkedin.com/in/dotrego/
    bio: Co-Founder of hybrix, the open source blockchain agnostic development platform.

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by wslyvh** [comment]
Added.

https://www.dutchblockchainweek.com/events/hybrix/
