### ISSUE TITLE
BitcoinWednesday.com

### ISSUE THREAD

**Issue by generalseven** [wslyvh/dutchblockchainweek#3]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Sample Template

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: This is a talk about blockchain. This field is indexed by search
  engines and used to show a description on /events.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: BitcoinWednesday.com

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    The Netherlands' Longest-Running Monthly Conference on Decentralization, Blockchain Tech, and Digital Currencies
  -
   
  -
    

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2019-06-05
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2019-06-05

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '18:00'
# Time when the event ends. Can be left empty.
endTime: '23:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://www.bitcoinwednesday.com/events/bitcoin-wednesday-72/

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 6

# The name of the venue where the event will be held. Can be left empty.
venue: 

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: 

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - panel
# - workshop
# Use _only_ one, and don't capitalize.
category: conference

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    # Required.
    name: 

    # Can be left empty.
    title: 

    # Can be left empty.
    company: 

    # The full URL, including http(s)://. Can be left empty.
    companyURL: https://BitcoinWednesday.com

    # Just the twitter handle, without Twitter's URL, nor the '@' symbol.
    # Can be left empty.
    twitter: 

    # The full URL, including http(s)://. Can be left empty.
    website: 

    # The bio is a single line.
    # Linebreaks are ignored, but they _must_ start with two spaces.
    bio: 
  -
    name: 
    title: 
    company: 
    companyURL: 
    twitter: 
    website: 
    bio: 
  -

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by wslyvh** [comment]
Added. 

Let me know, once you have more details on speakers & location.

**Comment by generalseven** [comment]
@wslyvh 

Something is really screwed up there.  See text on Hyperledger Project.  That's not our event on 5 June.

---

 Wednesday, 5 June
Bitcoin Wednesday - Atomic Swaps on Lightning

Join us in this deep dive into the Hyperledger Project, learn more about how different blockchains are being implemented, and how they will disrupt business as we know it.

Wednesday, 5 June @ 18:00-23:00 Event

**Comment by wslyvh** [comment]
My bad. Fixed now
