### ISSUE TITLE
Smilo Hybrid Blockchain & Decentralised Identifiers explained

### ISSUE THREAD

**Issue by elkanroelen** [wslyvh/dutchblockchainweek#6]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Smilo Hybrid Blockchain & Decentralised Identifiers explained

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: This is a talk about hybrid blockchains and Decentralised Identifiers. The possibilities and the solutions.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Smilo Hybrid Blockchain & Decentralised Identifiers explained

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    We start with a tech-friendly talk about decentralised blockchains, permissioned blockchains and hybrid blockchains. When the differences are clear we will reveal the importance of decentralisation and Identities.
  -
    There are many blockchain flavours out there. Smilo will explain the basics and how to choose for the correct implementation. Will it be decentralised? Permissioned? or maybe even hybrid?
  -
    With great technology we can do great things. Decentralised Identifiers is just one thing. We will explain the basics of decentralised Identifiers and the possibilities it will give.
  -
    We will end the evening with a network session and table talks. Share knowledge and experiences while enjoying a snack and a drink.

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2019-06-06
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2019-06-06

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '19:00'
# Time when the event ends. Can be left empty.
endTime: '22:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://www.meetup.com/nl-NL/Smilo-BFT-Meetup-Group/events/261479189/

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: Smilo Headquarters

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: Burgemeester Raveslootsingel 2 (Backdoor entrance, 5th floor), Almelo, Netherlands

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - panel
# - workshop
# Use _only_ one, and don't capitalize.
category: event

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    # Required.
    name: Elkan Roelen

    # Can be left empty.
    title: CEO & Co-founder of Smilo

    # Can be left empty.
    company: Smilo Platform

    # The full URL, including http(s)://. Can be left empty.
    companyURL: https://www.smilo.io

    # Just the twitter handle, without Twitter's URL, nor the '@' symbol.
    # Can be left empty.
    twitter: SmiloPlatform

    # The full URL, including http(s)://. Can be left empty.
    website: 

    # The bio is a single line.
    # Linebreaks are ignored, but they _must_ start with two spaces.
    bio: Elkan Roelen is a security expert, programmer and blockchain enthousiast
      known as a co-founder of Smilo.

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by wslyvh** [comment]
Added!

https://www.dutchblockchainweek.com/events/smilo/
